module.exports = [
   {
      head: "Hokimiyat haqida",
      list: [
         "Rahbariyat",
         "Markaziy apparat",
         "Boshqarma va tashkilotlar",
         "Elektron hukumat",
         "Bosh ish o`rinlar",
         "Rahbariyatning bayonotlari",
         "Matbuot xizmati",
         "Statistika",
         "Tarkibiy tuzilma",
         "Bog`lanish",
      ],
   },
   {
      head: "Faoliyat",
      list: [
         "Harakatlar strategiyasi",
         "Davlat dasturlari",
         "Normativ - huquqiy hujjatlar",
         "Loyihalar",
         "Investitsiya salohiyati",
         "Turizm faoliyati",
         "Xalqaro munosabat",
         "Jamoatchilik Kengashi",
         "Ochiq ma`lumotlar",
         "Ochiq majlislar",
         "Tadbirkorlik va biznes",
         "Iqtisodiy ko`rsatkichlar",
         "Ochiq tanlovlar",
         "Statistik hisobotlar",
      ],
   },
   {
      head: "Hokimiyat yangiliklari",
      list: [
         "Kapitalni yaxshilash",
         "Jamiyat va himoya",
         "Moliya va rivojlanish",
         "Transpor",
         "Madaniyat",
         "Afisha",
         "Mediateka",
         "Ommaviy tadbirlar",
         "Davlat ramzlari",
      ],
   },
   {
      head: "Yig'ilish",
      list: [
         "Kengash faoliyati",
         "Tuman kengashi deputatlari",
         "Muvofiqlashtiruvchi va maslahat organlari",
      ],
   },
   {
      head: "Xizmatlar",
      list: [
         "Interaktiv xizmatlar",
         "Fuqarolar murojaati",
         "Shahar transporti",
         "Mahalliy byudjetning daromad va xarajatlari",
         "Litsenziyalash xizmatlari",
         "Ko'p so'raladigan savollar",
         "Fuqarolardan taklif va mulohazalarini olish",
      ],
   },
   {
      head: "Shahar",
      list: [
         "Umumiy ma'lumotlar",
         "Qiziqarli joylar",
         "Shahar haritasi",
         "Parklar va dam olish madaniyati",
         "Fuqarolar uchun",
         "Biznes uchun",
         "Turistlar uchun",
         "O'zbekiston qahramoni",
      ],
   },
   {
      head: "Aksilkorrupsiya",
      list: [
         "Korrupsiyaga qarshi kurashish bo`yicha yangiliklar",
         "Sohaga oid normativ-huquqiy hujjatlar",
      ],
   },
];
