module.exports = [
   {
      head: "Hokimiyat haqida",
      list: [
         "Rahbariyat",
         "Markaziy apparat",
         "boshqarma va tashkilotlar",
         "Elektron hukumat",
         "Bosh ish o'rinlar",
         "Rahbariyat",
         "Markaziy apparat",
         "boshqarma va tashkilotlar",
         "Elektron hukumat",
         "Bosh ish o'rinlar",
      ],
   },
   {
      head: "Faoliyat",
      list: [
         "Rahbariyat",
         "Markaziy apparat",
         "boshqarma va tashkilotlar",
         "Elektron hukumat",
         "Bosh ish o'rinlar",
         "Rahbariyat",
         "Markaziy apparat",
         "boshqarma va tashkilotlar",
         "Elektron hukumat",
         "Bosh ish o'rinlar",
      ],
   },
   {
      head: "Hokimiyat yangiliklari",
      list: [
         "Rahbariyat",
         "Markaziy apparat",
         "boshqarma va tashkilotlar",
         "Elektron hukumat",
         "Bosh ish o'rinlar",
         "Rahbariyat",
         "Markaziy apparat",
         "boshqarma va tashkilotlar",
         "Elektron hukumat",
         "Bosh ish o'rinlar",
      ],
   },
   {
      head: "Yig'ilish",
      list: [
         "Rahbariyat",
         "Markaziy apparat",
         "boshqarma va tashkilotlar",
         "Elektron hukumat",
         "Bosh ish o'rinlar",
         "Rahbariyat",
         "Markaziy apparat",
         "boshqarma va tashkilotlar",
         "Elektron hukumat",
         "Bosh ish o'rinlar",
      ],
   },
   {
      head: "Xizmatlar",
      list: [
         "Rahbariyat",
         "Markaziy apparat",
         "boshqarma va tashkilotlar",
         "Elektron hukumat",
         "Bosh ish o'rinlar",
         "Rahbariyat",
         "Markaziy apparat",
         "boshqarma va tashkilotlar",
         "Elektron hukumat",
         "Bosh ish o'rinlar",
      ],
   },
];
