module.exports = [
   {
      head: "Hokimiyat haqida",
      list: [
         "Rahbariyat",
         "Markaziy apparat",
         "boshqarma va tashkilotlar",
         "Elektron hukumat",
         "Bosh ish o'rinlar",
         "Rahbariyat",
         "Markaziy apparat",
         "boshqarma va tashkilotlar",
         "Elektron hukumat",
         "Bosh ish o'rinlar",
      ],
   },
   {
      head: "Hokimiyat haqida",
      list: [
         "Rahbariyat",
         "Markaziy apparat",
         "boshqarma va tashkilotlar",
         "Elektron hukumat",
         "Bosh ish o'rinlar",
         "Rahbariyat",
         "Markaziy apparat",
         "boshqarma va tashkilotlar",
         "Elektron hukumat",
         "Bosh ish o'rinlar",
      ],
   },
   {
      head: "Hokimiyat haqida",
      list: [
         "Rahbariyat",
         "Markaziy apparat",
         "boshqarma va tashkilotlar",
         "Elektron hukumat",
         "Bosh ish o'rinlar",
         "Rahbariyat",
         "Markaziy apparat",
         "boshqarma va tashkilotlar",
         "Elektron hukumat",
         "Bosh ish o'rinlar",
      ],
   },
   {
      head: "Hokimiyat haqida",
      list: [
         "Rahbariyat",
         "Markaziy apparat",
         "boshqarma va tashkilotlar",
         "Elektron hukumat",
         "Bosh ish o'rinlar",
         "Rahbariyat",
         "Markaziy apparat",
         "boshqarma va tashkilotlar",
         "Elektron hukumat",
         "Bosh ish o'rinlar",
      ],
   },
   {
      head: "Hokimiyat haqida",
      list: [
         "Rahbariyat",
         "Markaziy apparat",
         "boshqarma va tashkilotlar",
         "Elektron hukumat",
         "Bosh ish o'rinlar",
         "Rahbariyat",
         "Markaziy apparat",
         "boshqarma va tashkilotlar",
         "Elektron hukumat",
         "Bosh ish o'rinlar",
      ],
   },
];
